// @ts-check
import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel';

const SITE = 'https://lipboxes.com';

export default defineConfig({
  site: SITE,
  trailingSlash: 'always',
  output: 'static',
  adapter: vercel({
    // Images are pre-generated at build time, so no runtime image service.
    imageService: false,
    webAnalytics: { enabled: false },
  }),
  build: {
    format: 'directory',
    inlineStylesheets: 'always',
  },
  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'hover',
  },
  // The sitemap is generated by src/pages/sitemap.xml.ts so it lands at
  // /sitemap.xml exactly, carries image entries, and excludes noindex pages.
  integrations: [],
  vite: {
    build: {
      sourcemap: false,
      cssMinify: 'lightningcss',
      // Emit every script as an external file. Inlined scripts would be blocked
      // by the strict `script-src 'self'` Content Security Policy in
      // vercel.json, which would silently break the navigation.
      assetsInlineLimit: 0,
    },
  },
});
